### ISSUE TITLE
about connect

### ISSUE THREAD

**Issue by drapelli** [swstephe/py2jdbc#5]
i was install py2jdbc in python ]
and i was try connect a single sqlite database 

but it show this error message 

OSError: [WinError 193] %1 não é um aplicativo Win32 válido

the complite trace was there 

PS C:\Users\xxx\Documents> & C:/Users/xxx/AppData/Local/Programs/Python/Python39/python.exe c:/Users/xxx/Documents/p01/novo.py
Traceback (most recent call last):
  File "c:\Users\xxx\Documents\p01\novo.py", line 1, in <module>
    import py2jdbc
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\py2jdbc\__init__.py", line 2, in <module>
    from py2jdbc.dbi import (
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\py2jdbc\dbi.py", line 6, in <module>
    from py2jdbc.wrap import get_env
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\py2jdbc\wrap.py", line 4, in <module>
    import py2jdbc.jni
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\py2jdbc\jni.py", line 2619, in <module>
    libjvm = CDLL(find_libjvm())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 não é um aplicativo Win32 válido

please you can help me about whats happen
i using vs code and windows 10 

thanks

**Comment by swstephe** [comment]
On Windows, you need to set JDK_HOME environment variable to the location for a JDK so it can locate the DLL.
